[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "eros-view"
authors = [
    {name = "Floris Vernieuwe", email = "floris@vernieuwe.eu"},
]
description = "A package to view EROS logs"
readme = "readme.md"
requires-python = ">=3.9"
license = {text = "GPL-3.0"}
classifiers = [
    "Programming Language :: Python :: 3",
]

dependencies = [
    "click==8.1.3",
    "eros@git+https://github.com/Florioo/eros-python.git"
]

dynamic = ["version"]

[project.scripts]
eros-view = "main:eros_log"
